/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Agreements {
  appointment_id: string | null;
  client_key: Generated<string>;
  consent_text_version: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  document_type: string;
  id: Generated<string>;
  pdf_path: string;
  sha256: string;
  signed_at: Timestamp;
  signer_ip: string | null;
  signer_name: string;
  signer_user_agent: string | null;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Applications {
  amended_from: string | null;
  amendment_reason: string | null;
  amount_unit: string | null;
  application_address: string | null;
  applicator_license_no: string | null;
  applicator_name: string | null;
  applied_at: Timestamp | null;
  appointment_id: string;
  area_treated: Numeric | null;
  area_unit: string | null;
  business_address: string | null;
  business_license_no: string | null;
  business_name: string | null;
  captured_at: Timestamp | null;
  client_key: string;
  created_at: Generated<Timestamp>;
  customer_address: string | null;
  customer_name: string | null;
  customer_statement_at: Timestamp | null;
  epa_reg_no: string | null;
  external_ref: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  imported: Generated<boolean>;
  mix_rate: Numeric | null;
  mix_unit: string | null;
  product_id: string | null;
  product_kind: string | null;
  product_name: string | null;
  recorded_at: Generated<Timestamp>;
  restricted_use: boolean | null;
  signal_word: string | null;
  source: Generated<string>;
  state_template: Generated<string>;
  target_pests: Generated<string[]>;
  target_sites: Generated<string[]>;
  technician_id: string | null;
  tenant_id: Generated<string>;
  total_amount: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface Appointments {
  arrived_at: Timestamp | null;
  cancel_reason: string | null;
  checklist_results: Json | null;
  client_key: Generated<string>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  customer_id: string;
  detached: Generated<boolean>;
  duration_min: Generated<number>;
  en_route_at: Timestamp | null;
  external_ref: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  is_initial: Generated<boolean>;
  local_date: string | null;
  notes: string | null;
  occurrence_date: string | null;
  price_cents: number | null;
  property_id: string;
  sequence: number | null;
  service_type_id: string;
  shadow: Generated<boolean>;
  signer_name: string | null;
  skip_reason: string | null;
  source: Generated<string>;
  status: Generated<string>;
  subscription_id: string | null;
  tech_notes: string | null;
  technician_id: string | null;
  tenant_id: Generated<string>;
  tz: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  window_end: string | null;
  window_start: string | null;
}

export interface Attachments {
  captured_at: Timestamp | null;
  client_key: Generated<string>;
  content_type: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string | null>;
  id: Generated<string>;
  kind: string;
  owner_id: string;
  owner_type: string;
  path: string;
  sha256: string | null;
  size_bytes: number;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  uploaded_at: Timestamp | null;
}

export interface AuditLog {
  action: string;
  actor_id: string | null;
  actor_role: string | null;
  after: Json | null;
  at: Generated<Timestamp>;
  before: Json | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  row_id: string;
  table_name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface BillingRuns {
  created_at: Generated<Timestamp>;
  failures: Generated<Json>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  invoices_created: Generated<number>;
  payments_posted: Generated<number>;
  started_at: Generated<Timestamp>;
  started_by: Generated<string | null>;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Commissions {
  amount_cents: number;
  basis_cents: number;
  created_at: Generated<Timestamp>;
  created_by: Generated<string | null>;
  customer_id: string;
  decided_at: Timestamp | null;
  decided_by: string | null;
  flat_cents: number;
  id: Generated<string>;
  note: string | null;
  pct: Numeric;
  status: Generated<string>;
  subscription_id: string | null;
  technician_id: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface CustomerBalances {
  balance_cents: number | null;
  customer_id: string | null;
  last_activity_at: Timestamp | null;
  tenant_id: string | null;
}

export interface Customers {
  alt_phone: string | null;
  billing_address_line1: string | null;
  billing_address_line2: string | null;
  billing_city: string | null;
  billing_postal_code: string | null;
  billing_region: string | null;
  /**
   * ENG-01: per-form-render key; a retry returns the existing customer.
   */
  client_key: string | null;
  company_name: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string | null;
  email_opt_in: Generated<boolean>;
  email_opt_in_at: Timestamp | null;
  email_unsubscribed_at: Timestamp | null;
  external_ref: string | null;
  first_name: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  kind: Generated<string>;
  last_name: string | null;
  notes: string | null;
  phone: string | null;
  search_text: Generated<string | null>;
  sms_consent_at: Timestamp | null;
  sms_consent_source: string | null;
  sms_opted_out_at: Timestamp | null;
  sold_by_technician_id: string | null;
  source: Generated<string>;
  status: Generated<string>;
  stripe_customer_id: string | null;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Exports {
  created_at: Generated<Timestamp>;
  error: string | null;
  expires_at: Timestamp | null;
  format_version: Generated<string>;
  id: Generated<string>;
  path: string | null;
  progress: Generated<Json>;
  requested_by: Generated<string | null>;
  size_bytes: number | null;
  status: Generated<string>;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ImportJobs {
  committed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string | null>;
  delta_of: string | null;
  dry_run_report: Json | null;
  error: string | null;
  files: Generated<Json>;
  id: Generated<string>;
  mapping_ids: Generated<string[]>;
  reconcile_report: Json | null;
  rollback_deadline: Timestamp | null;
  rolled_back_at: Timestamp | null;
  shadow: Generated<boolean>;
  source: string;
  stats: Generated<Json>;
  status: Generated<string>;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ImportMappings {
  column_map: Generated<Json>;
  created_at: Generated<Timestamp>;
  entity: string;
  header_signature: Generated<string[]>;
  id: Generated<string>;
  is_preset: Generated<boolean>;
  name: string;
  source: string;
  tenant_id: Generated<string | null>;
  transforms: Generated<Json>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ImportRows {
  action: string | null;
  created_at: Generated<Timestamp>;
  entity: string;
  external_ref: string | null;
  file_name: string;
  id: Generated<string>;
  job_id: string;
  mapped: Json | null;
  raw: Json;
  reasons: Generated<string[]>;
  row_number: number;
  status: Generated<string>;
  target_id: string | null;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface InvoiceBalances {
  customer_id: string | null;
  due_date: string | null;
  invoice_id: string | null;
  number: number | null;
  open_cents: number | null;
  status: string | null;
  tenant_id: string | null;
  total_cents: number | null;
}

export interface InvoiceLines {
  amount_cents: number;
  appointment_id: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  invoice_id: string;
  quantity: Generated<Numeric>;
  tenant_id: Generated<string>;
  unit_amount_cents: number;
  updated_at: Generated<Timestamp>;
}

export interface Invoices {
  appointment_id: string | null;
  autopay_attempts: Generated<number>;
  autopay_last_error: string | null;
  autopay_next_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  customer_id: string;
  due_date: string | null;
  external_ref: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  issued_at: Timestamp | null;
  number: number;
  paid_at: Timestamp | null;
  period_key: string;
  source: Generated<string>;
  status: Generated<string>;
  subscription_id: string | null;
  tenant_id: Generated<string>;
  total_cents: number;
  updated_at: Generated<Timestamp>;
  void_reason: string | null;
  voided_at: Timestamp | null;
}

export interface LedgerEntries {
  amount_cents: number;
  created_at: Generated<Timestamp>;
  created_by: Generated<string | null>;
  customer_id: string;
  entry_key: string;
  external_ref: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  invoice_id: string | null;
  memo: string | null;
  occurred_at: Generated<Timestamp>;
  payment_id: string | null;
  source: Generated<string>;
  tenant_id: Generated<string>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  display_name: string | null;
  email: string | null;
  id: Generated<string>;
  invited_by: string | null;
  role: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Messages {
  appointment_id: string | null;
  billed_units: Generated<number>;
  channel: string;
  cost_cents: Generated<number>;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  error: string | null;
  id: Generated<string>;
  invoice_id: string | null;
  outbox_event_id: string | null;
  provider: string | null;
  provider_id: string | null;
  recipient: string;
  sent_at: Timestamp | null;
  status: Generated<string>;
  suppressed_reason: string | null;
  template: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Offices {
  address_line1: string;
  address_line2: string | null;
  business_license_no: string | null;
  city: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  location: string | null;
  name: string;
  phone: string | null;
  postal_code: string;
  region: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface OutboxEvents {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  channel: string;
  created_at: Generated<Timestamp>;
  event_id: string;
  id: Generated<string>;
  last_error: string | null;
  locked_until: Timestamp | null;
  payload: Generated<Json>;
  priority: Generated<number>;
  sent_at: Timestamp | null;
  tenant_id: Generated<string>;
  topic: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentMethods {
  consent_text: string;
  consented_at: Timestamp;
  created_at: Generated<Timestamp>;
  customer_id: string;
  exp_month: number | null;
  exp_year: number | null;
  id: Generated<string>;
  kind: string;
  label: string;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  status: Generated<string>;
  stripe_mandate_id: string | null;
  stripe_payment_method_id: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Payments {
  amount_cents: number;
  appointment_id: string | null;
  check_number: string | null;
  client_payment_key: string;
  collected_by: Generated<string | null>;
  created_at: Generated<Timestamp>;
  customer_id: string;
  external_ref: string | null;
  failure_code: string | null;
  failure_message: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  invoice_id: string | null;
  method: string;
  payment_method_id: string | null;
  received_at: Timestamp | null;
  refunded_cents: Generated<number>;
  source: Generated<string>;
  status: Generated<string>;
  stripe_checkout_session_id: string | null;
  stripe_payment_intent_id: string | null;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PortalTokens {
  created_at: Generated<Timestamp>;
  customer_id: string;
  expires_at: Timestamp;
  id: Generated<string>;
  tenant_id: string;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  used_at: Timestamp | null;
}

export interface Products {
  active: Generated<boolean>;
  active_ingredients: string | null;
  created_at: Generated<Timestamp>;
  default_amount_unit: string | null;
  default_mix_rate: Numeric | null;
  default_mix_unit: string | null;
  epa_reg_no: string | null;
  external_ref: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  kind: Generated<string>;
  name: string;
  restricted_use: Generated<boolean>;
  signal_word: string | null;
  source: Generated<string>;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Properties {
  access_notes: string | null;
  address_line1: string;
  address_line2: string | null;
  city: string;
  created_at: Generated<Timestamp>;
  customer_id: string;
  external_ref: string | null;
  geocode_confidence: Numeric | null;
  geocode_source: string | null;
  geocoded_at: Timestamp | null;
  id: Generated<string>;
  import_job_id: string | null;
  label: string | null;
  lawn_area_sq_ft: number | null;
  location: string | null;
  location_confirmed_at: Timestamp | null;
  location_confirmed_by: string | null;
  location_locked: Generated<boolean>;
  postal_code: string;
  region: string;
  source: Generated<string>;
  sq_ft: number | null;
  status: Generated<string>;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ReconciliationIssues {
  created_at: Generated<Timestamp>;
  details: string;
  found_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  payment_id: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  stripe_object_id: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface RouteAiRuns {
  created_at: Generated<Timestamp>;
  error: string | null;
  expected: Json;
  finished_at: Timestamp | null;
  id: Generated<string>;
  lease_until: Timestamp | null;
  local_date: string;
  model: string | null;
  request_key: string;
  requested_by: Generated<string | null>;
  result: Json | null;
  started_at: Timestamp | null;
  state: Generated<Json>;
  status: Generated<string>;
  technician_id: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  usage: Generated<Json>;
}

export interface Routes {
  created_at: Generated<Timestamp>;
  flagged_stops: Generated<number>;
  id: Generated<string>;
  local_date: string;
  optimized_at: Timestamp | null;
  optimizer: string | null;
  previous_order: Json | null;
  published_at: Timestamp | null;
  published_by: string | null;
  published_order: Json | null;
  run_id: string | null;
  stats: Generated<Json>;
  technician_id: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface ServicePlans {
  active: Generated<boolean>;
  billing_mode: Generated<string>;
  created_at: Generated<Timestamp>;
  default_duration_min: number | null;
  external_ref: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  initial_price_cents: number | null;
  name: string;
  price_cents: number;
  rrule: string;
  service_type_id: string;
  source: Generated<string>;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ServiceRequests {
  created_at: Generated<Timestamp>;
  customer_id: string;
  handled_at: Timestamp | null;
  handled_by: string | null;
  id: Generated<string>;
  message: string;
  preferred_times: string | null;
  property_id: string | null;
  request_key: string;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ServiceTypes {
  active: Generated<boolean>;
  category: string;
  checklist: Generated<Json>;
  created_at: Generated<Timestamp>;
  default_duration_min: Generated<number>;
  id: Generated<string>;
  name: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Subscriptions {
  autopay: Generated<boolean>;
  billing_mode: string;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  customer_id: string;
  duration_min: Generated<number>;
  external_ref: string | null;
  generated_through: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  initial_price_cents: number | null;
  next_service_date: string | null;
  notes: string | null;
  pause_reason: string | null;
  paused_from: string | null;
  paused_until: string | null;
  plan_id: string;
  preferred_technician_id: string | null;
  preferred_window_end: string | null;
  preferred_window_start: string | null;
  price_cents: number;
  property_id: string;
  rrule: string;
  service_type_id: string;
  source: Generated<string>;
  start_date: string;
  status: Generated<string>;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface SyncConflicts {
  appointment_id: string;
  client_key: string;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  id: Generated<string>;
  kind: string;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  technician_id: string | null;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TechDayNotices {
  client_key: string;
  created_at: Generated<Timestamp>;
  delay_min: number;
  id: Generated<string>;
  kind: string;
  local_date: string;
  technician_id: string;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Technicians {
  active: Generated<boolean>;
  applicator_license_no: string;
  categories: Generated<string[]>;
  color_index: Generated<number>;
  created_at: Generated<Timestamp>;
  display_name: string;
  external_ref: string | null;
  id: Generated<string>;
  import_job_id: string | null;
  license_expiry: string;
  phone: string | null;
  source: Generated<string>;
  tenant_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Tenants {
  brand_accent: string | null;
  business_license_no: string;
  /**
   * ENG-01: a double-submitted signup form creates one tenant, not two.
   */
  client_key: string | null;
  commission_flat_cents: Generated<number>;
  commission_pct: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  logo_path: string | null;
  /**
   * FR-MIG-19: customer messaging stays suppressed for imported records until the owner clicks Go live.
   */
  messaging_live_at: Timestamp | null;
  name: string;
  plan: Generated<string>;
  settings: Generated<Json>;
  state: string;
  stripe_account_id: string | null;
  stripe_charges_enabled: Generated<boolean>;
  stripe_details_submitted: Generated<boolean>;
  stripe_reconciled_at: Timestamp | null;
  tech_sales_enabled: Generated<boolean>;
  timezone: string;
  updated_at: Generated<Timestamp>;
  /**
   * D-14: white label purchased; removes the product credit from everything customers see (FR-BRD-03).
   */
  white_label_at: Timestamp | null;
}

export interface WebhookEvents {
  created_at: Generated<Timestamp>;
  error: string | null;
  event_id: string;
  id: Generated<string>;
  payload: Json;
  processed_at: Timestamp | null;
  provider: string;
  received_at: Generated<Timestamp>;
  tenant_id: string | null;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  agreements: Agreements;
  applications: Applications;
  appointments: Appointments;
  attachments: Attachments;
  audit_log: AuditLog;
  billing_runs: BillingRuns;
  commissions: Commissions;
  customer_balances: CustomerBalances;
  customers: Customers;
  exports: Exports;
  import_jobs: ImportJobs;
  import_mappings: ImportMappings;
  import_rows: ImportRows;
  invoice_balances: InvoiceBalances;
  invoice_lines: InvoiceLines;
  invoices: Invoices;
  ledger_entries: LedgerEntries;
  memberships: Memberships;
  messages: Messages;
  offices: Offices;
  outbox_events: OutboxEvents;
  payment_methods: PaymentMethods;
  payments: Payments;
  portal_tokens: PortalTokens;
  products: Products;
  properties: Properties;
  reconciliation_issues: ReconciliationIssues;
  route_ai_runs: RouteAiRuns;
  routes: Routes;
  service_plans: ServicePlans;
  service_requests: ServiceRequests;
  service_types: ServiceTypes;
  subscriptions: Subscriptions;
  sync_conflicts: SyncConflicts;
  tech_day_notices: TechDayNotices;
  technicians: Technicians;
  tenants: Tenants;
  webhook_events: WebhookEvents;
}
