// Generates app/tokens.css from replica/design/tokens.json (the single source
// of truth). Run `npm run design:tokens` after editing the JSON; CI fails if the
// committed CSS is stale (`--check`).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const tokens = JSON.parse(readFileSync(join(root, "replica/design/tokens.json"), "utf8"));
const out = join(root, "app/tokens.css");

const themeVars = (theme) =>
  Object.entries(tokens.color[theme])
    .map(([role, hex]) => `  --rk-${role}: ${hex};`)
    .join("\n");

const routeEntries = Object.entries(tokens.route).filter(([k]) => !k.startsWith("_"));
const routeVars = routeEntries
  .flatMap(([k, hex]) => [`  --rk-route-${k}: ${hex};`, `  --rk-route-ink-${k}: ${tokens.route_ink[k]};`])
  .join("\n");

// Route colours carry initials and stop numbers, so their ink must pass AA too.
function luminance(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255);
  const ch = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b);
}
function ratio(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}
const failing = routeEntries.filter(([k, hex]) => ratio(hex, tokens.route_ink[k]) < 4.5);
if (failing.length) {
  console.error(`route ink fails AA for: ${failing.map(([k]) => k).join(", ")}`);
  process.exit(1);
}

const css = `/* Generated by scripts/design/build-tokens.mjs from replica/design/tokens.json. Do not edit. */

:root {
  color-scheme: light;
${themeVars("light")}
${routeVars}
  --rk-shadow-raised: ${tokens.shadow.raised};
  --rk-shadow-overlay: ${tokens.shadow.overlay};
  --rk-ease: ${tokens.motion.ease};
  --rk-fast: ${tokens.motion.fast};
  --rk-base: ${tokens.motion.base};
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]):not([data-theme="outdoor"]) {
    color-scheme: dark;
${themeVars("dark").replace(/^/gm, "  ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${themeVars("dark")}
}

/* FR-TEC-11: outdoor high-contrast mode for the technician app. */
:root[data-theme="outdoor"] {
  color-scheme: light;
${themeVars("outdoor")}
}
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(out, "utf8");
  if (current !== css) {
    console.error("app/tokens.css is stale. Run: npm run design:tokens");
    process.exit(1);
  }
  console.log("app/tokens.css is up to date");
} else {
  writeFileSync(out, css);
  console.log("wrote app/tokens.css");
}
